# Generated by Django 3.2 on 2021-05-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210517_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'ordering': ['-hotel_room_type__price']},
        ),
        migrations.AlterField(
            model_name='booked',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_apartment', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='hotel_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_hotel_room', to='listings.hotelroom'),
        ),
    ]
